#include "dictionary_arrays.h"

char *italianPortugueseFrench[250][3] = {
        {"ciao", "olá", "bonjour"}, {"mondo", "mundo", "monde"}, {"computer", "computador", "ordinateur"},
        {"scienza", "ciência", "science"}, {"mela", "maçã", "pomme"}, {"libro", "livro", "livre"},
        {"gatto", "gato", "chat"}, {"cane", "cão", "chien"}, {"topo", "rato", "souris"}, {"casa", "casa", "maison"},
        {"albero", "árvore", "arbre"}, {"fiore", "flor", "fleur"}, {"acqua", "água", "eau"},
        {"fuoco", "fogo", "feu"}, {"terra", "terra", "terre"}, {"aria", "ar", "air"},
        {"cielo", "céu", "ciel"}, {"stella", "estrela", "étoile"}, {"sole", "sol", "soleil"},
        {"luna", "lua", "lune"}, {"auto", "carro", "voiture"}, {"treno", "trem", "train"},
        {"nave", "navio", "bateau"}, {"aereo", "avião", "avion"}, {"bicicletta", "bicicleta", "vélo"},
        {"strada", "estrada", "route"}, {"ponte", "ponte", "pont"}, {"scuola", "escola", "école"},
        {"università", "universidade", "université"}, {"insegnante", "professor", "professeur"},
        {"studente", "estudante", "étudiant"}, {"quaderno", "caderno", "cahier"}, {"penna", "caneta", "stylo"},
        {"carta", "papel", "papier"}, {"tavolo", "mesa", "table"}, {"sedia", "cadeira", "chaise"},
        {"finestra", "janela", "fenêtre"}, {"porta", "porta", "porte"}, {"giorno", "dia", "jour"},
        {"notte", "noite", "nuit"}, {"mattina", "manhã", "matin"}, {"sera", "noite", "soir"},
        {"amico", "amigo", "ami"}, {"famiglia", "família", "famille"}, {"bambino", "criança", "enfant"},
        {"genitore", "pai", "parent"}, {"madre", "mãe", "mère"}, {"padre", "pai", "père"},
        {"fratello", "irmão", "frère"}, {"sorella", "irmã", "sœur"}, {"zio", "tio", "oncle"},
        {"zia", "tia", "tante"}, {"cugino", "primo", "cousin"}, {"cugina", "prima", "cousine"},
        {"nonna", "avó", "grand-mère"}, {"nonno", "avô", "grand-père"}, {"figlio", "filho", "fils"},
        {"figlia", "filha", "fille"}, {"uomo", "homem", "homme"}, {"donna", "mulher", "femme"},
        {"ragazzo", "menino", "garçon"}, {"ragazza", "menina", "fille"}, {"bambino", "bebê", "bébé"},
        {"amore", "amor", "amour"}, {"speranza", "esperança", "espoir"}, {"gioia", "alegria", "joie"},
        {"paura", "medo", "peur"}, {"tristezza", "tristeza", "tristesse"}, {"rabbia", "raiva", "colère"},
        {"pace", "paz", "paix"}, {"guerra", "guerra", "guerre"}, {"vita", "vida", "vie"},
        {"morte", "morte", "mort"}, {"salute", "saúde", "santé"}, {"malattia", "doença", "maladie"},
        {"medico", "médico", "médecin"}, {"ospedale", "hospital", "hôpital"}, {"medicina", "medicina", "médecine"},
        {"chirurgia", "cirurgia", "chirurgie"}, {"infermiera", "enfermeira", "infirmière"}, {"cura", "cuidado", "soin"},
        {"rimedio", "remédio", "remède"}, {"farmaco", "medicamento", "médicament"}, {"tempo", "tempo", "temps"},
        {"ora", "hora", "heure"}, {"minuto", "minuto", "minute"}, {"secondo", "segundo", "seconde"},
        {"giorno", "dia", "jour"}, {"settimana", "semana", "semaine"}, {"mese", "mês", "mois"},
        {"anno", "ano", "année"}, {"eternità", "eternidade", "éternité"}, {"passato", "passado", "passé"},
        {"presente", "presente", "présent"}, {"futuro", "futuro", "avenir"}, {"storia", "história", "histoire"},
        {"memoria", "memória", "mémoire"}, {"sogno", "sonho", "rêve"}, {"pensiero", "pensamento", "pensée"},
        {"idea", "idéia", "idée"}, {"immaginazione", "imaginação", "imagination"}, {"spirito", "espírito", "esprit"},
        {"anima", "alma", "âme"}, {"corpo", "corpo", "corps"}, {"cuore", "coração", "cœur"},
        {"sangue", "sangue", "sang"}, {"osso", "osso", "os"}, {"pelle", "pele", "peau"},
        {"capello", "cabelo", "cheveu"}, {"occhio", "olho", "œil"}, {"orecchio", "orelha", "oreille"},
        {"bocca", "boca", "bouche"}, {"dente", "dente", "dent"}, {"lingua", "língua", "langue"},
        {"naso", "nariz", "nez"}, {"mano", "mão", "main"}, {"piede", "pé", "pied"},
        {"braccio", "braço", "bras"}, {"gamba", "perna", "jambe"}, {"ventre", "ventre", "ventre"},
        {"schiena", "costas", "dos"}, {"testa", "cabeça", "tête"}, {"cervello", "cérebro", "cerveau"},
        {"muscolo", "músculo", "muscle"}, {"nervo", "nervo", "nerf"}, {"articolazione", "articulação", "articulation"},
        {"pelle", "pele", "peau"}, {"vena", "veia", "veine"}, {"arteria", "artéria", "artère"},
        {"nervo", "nervo", "nerf"}, {"cellula", "célula", "cellule"}, {"batterio", "bactéria", "bactérie"},
        {"virus", "vírus", "virus"}, {"malattia", "doença", "maladie"}, {"febbre", "febre", "fièvre"},
        {"dolore", "dor", "douleur"}, {"ferita", "ferida", "blessure"}, {"frattura", "fratura", "fracture"},
        {"ustione", "queimadura", "brûlure"}, {"cicatrice", "cicatriz", "cicatrice"}, {"cura", "cuidado", "soin"},
        {"trattamento", "tratamento", "traitement"}, {"medicazione", "medicação", "médication"}, {"prescrizione", "receita", "prescription"},
        {"siero", "soro", "sérum"}, {"vaccino", "vacina", "vaccin"}, {"antibiotico", "antibiótico", "antibiotique"},
        {"analgesico", "analgésico", "analgésique"}, {"antidoto", "antídoto", "antidote"}, {"epidemia", "epidemia", "épidémie"},
        {"pandemia", "pandemia", "pandémie"}, {"vaccinazione", "vacinação", "vaccination"}, {"trattamento", "tratamento", "traitement"},
        {"cura", "cuidado", "soin"}, {"operazione", "operação", "opération"}, {"chirurgia", "cirurgia", "chirurgie"},
        {"trapianto", "transplante", "greffe"}, {"anestesia", "anestesia", "anesthésie"}, {"riabilitazione", "reabilitação", "rééducation"},
        {"terapia", "terapia", "thérapie"}, {"psicoterapia", "psicoterapia", "psychothérapie"}, {"psichiatria", "psiquiatria", "psychiatrie"},
        {"neurologia", "neurologia", "neurologie"}, {"cardiologia", "cardiologia", "cardiologie"}, {"pneumologia", "pneumologia", "pneumologie"},
        {"gastroenterologia", "gastroenterologia", "gastroentérologie"}, {"dermatologia", "dermatologia", "dermatologie"}, {"endocrinologia", "endocrinologia", "endocrinologie"},
        {"oncologia", "oncologia", "oncologie"}, {"ginecologia", "ginecologia", "gynécologie"}, {"urologia", "urologia", "urologie"},
        {"ortopedia", "ortopedia", "orthopédie"}, {"pediatria", "pediatria", "pédiatrie"}, {"ostetricia", "obstetrícia", "obstétrique"},
        {"oftalmologia", "oftalmologia", "ophtalmologie"}, {"otorinolaringoiatria", "otorrinolaringologia", "otorhinolaryngologie"}, {"reumatologia", "reumatologia", "rhumatologie"},
        {"ematologia", "hematologia", "hématologie"}, {"immunologia", "imunologia", "immunologie"}, {"allergologia", "alergologia", "allergologie"},
        {"geriatria", "geriatria", "gériatrie"}, {"neonatologia", "neonatologia", "néonatologie"}, {"anatomia", "anatomia", "anatomie"},
        {"fisiologia", "fisiologia", "physiologie"}, {"patologia", "patologia", "pathologie"}, {"istologia", "histologia", "histologie"},
        {"citologia", "citologia", "cytologie"}, {"genetica", "genética", "génétique"}, {"biologia", "biologia", "biologie"},
        {"biochimica", "bioquímica", "biochimie"}, {"biofisica", "biofísica", "biophysique"}, {"biotecnologia", "biotecnologia", "biotechnologie"},
        {"farmacologia", "farmacologia", "pharmacologie"}, {"tossicologia", "toxicologia", "toxicologie"}, {"farmaco", "medicamento", "médicament"},
        {"farmacia", "farmácia", "pharmacie"}, {"posologia", "posologia", "posologie"}, {"dose", "dose", "dose"},
        {"concentrazione", "concentração", "concentration"}, {"formulazione", "formulação", "formulation"}, {"precauzione", "precaução", "précaution"},
        {"controindicazione", "contraindicação", "contre-indication"}, {"effetto collaterale", "efeito colateral", "effet secondaire"}, {"interazione", "interação", "interaction"},
        {"dipendenza", "dependência", "accoutumance"}, {"astinenza", "abstinência", "sevrage"}, {"allergia", "alergia", "allergie"},
        {"intolleranza", "intolerância", "intolérance"}, {"ipersensibilità", "hipersensibilidade", "hypersensibilité"}, {"shock", "choque", "choc"},
        {"coma", "coma", "coma"}, {"morte", "morte", "mort"}, {"soccorso", "resgate", "secours"},
        {"emergenza", "emergência", "urgence"}, {"ospedale", "hospital", "hôpital"}, {"ambulanza", "ambulância", "ambulance"},
        {"paramedico", "paramédico", "secouriste"}, {"medico", "médico", "médecin"}, {"infermiera", "enfermeira", "infirmière"},
        {"chirurgo", "cirurgião", "chirurgien"}, {"anestesista", "anestesista", "anesthésiste"}, {"resuscitatore", "resuscitador", "réanimateur"},
        {"pediatra", "pediatra", "pédiatre"}, {"ginecologo", "ginecólogo", "gynécologue"}, {"oftalmologo", "oftalmólogo", "ophtalmologue"},
        {"dentista", "dentista", "dentiste"}, {"farmacista", "farmacêutico", "pharmacien"}, {"ostetrica", "parteira", "sage-femme"},
        {"fisioterapista", "fisioterapeuta", "kinésithérapeute"}, {"psicologo", "psicólogo", "psychologue"}, {"psichiatra", "psiquiatra", "psychiatre"},
        {"cardiologo", "cardiólogo", "cardiologue"}, {"pneumologo", "neumólogo", "pneumologue"}, {"gastroenterologo", "gastroenterólogo", "gastroentérologue"},
        {"dermatologo", "dermatólogo", "dermatologue"}, {"endocrinologo", "endocrinólogo", "endocrinologue"}, {"oncologo", "oncólogo", "oncologue"},
        {"reumatologo", "reumatólogo", "rhumatologue"}, {"ematologo", "hematólogo", "hématologue"}, {"immunologo", "inmunólogo", "immunologue"},
        {"allergologo", "alergólogo", "allergologue"}, {"geriatra", "geriatra", "gériatre"}, {"neonatologo", "neonatólogo", "néonatologue"},
        {"anatomista", "anatomista", "anatomiste"}, {"fisiologo", "fisiólogo", "physiologiste"}, {"patologo", "patólogo", "pathologiste"},
        {"istologo", "histólogo", "histologiste"}, {"citologo", "citólogo", "cytologiste"}, {"genetista", "genetista", "généticien"},
        {"biologo", "biólogo", "biologiste"},
};
